global:
  scrape_interval: 15s
rule_files:
  - "alert_active_connections.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'django-app-blue'
    metrics_path: /metrics
    static_configs:
      - targets: ['app_blue:8000']
  # - job_name: 'django-health-blue'
  #   metrics_path: /health
  #   static_configs:
  #     - targets: ['app_blue:8000']
  - job_name: 'django-app-green'
    static_configs:
      - targets: ['app_green:8000']
    metrics_path: /metrics
  # - job_name: 'django-health-green'
  #   static_configs:
  #     - targets: ['app_green:8000']
  #   metrics_path: /health
